import { Ticket } from "./types";

// Mock data based on superhero theme
export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "T-001",
    customerName: "Tony Stark",
    email: "ironman@stark.com",
    body: "J.A.R.V.I.S. is auto-purchasing distinct shawarma joints again. I need to cap the AI spending limit immediately.",
    priority: "High",
    category: "Billing",
    status: "Open",
    createdAt: "2023-10-27T10:00:00Z",
  },
  {
    id: "T-002",
    customerName: "Bruce Banner",
    email: "hulk@avengers.org",
    body: "THE APP CRASHES WHEN I TYPE IN CAPS LOCK! HULK SMASH KEYBOARD!",
    priority: "High",
    category: "Bug",
    status: "Open",
    createdAt: "2023-10-27T10:15:00Z",
  },
  {
    id: "T-003",
    customerName: "Peter Parker",
    email: "spidey@queens.ny",
    body: "My web-fluid subscription didn’t renew. I’m currently hanging upside down from the Empire State Building. Please help.",
    priority: "High",
    category: "Billing",
    status: "Open",
    createdAt: "2023-10-27T11:30:00Z",
  },
  {
    id: "T-004",
    customerName: "Thor Odinson",
    email: "pointbreak@asgard.gov",
    body: "I cannot find the setting to change my location to Asgard. The GPS keeps defaulting to Oklahoma.",
    priority: "Medium",
    category: "Bug",
    status: "Open",
    createdAt: "2023-10-27T12:00:00Z",
  },
  {
    id: "T-005",
    customerName: "Natasha Romanoff",
    email: "widow@shield.gov",
    body: "Requesting a feature to auto-delete chat logs after 30 seconds. Operational security is critical.",
    priority: "Medium",
    category: "Feature Request",
    status: "Open",
    createdAt: "2023-10-27T12:30:00Z",
  },
  {
    id: "T-006",
    customerName: "Steve Rogers",
    email: "cap@history.com",
    body: "How do I turn off the notifications? They keep dinging while I am trying to listen to the phonograph.",
    priority: "Low",
    category: "General",
    status: "Open",
    createdAt: "2023-10-27T13:00:00Z",
  },
  {
    id: "T-007",
    customerName: "Wanda Maximoff",
    email: "witch@westview.nj",
    body: "The reality distortion filter is glitching. My neighbors are turning into 1950s sitcom characters.",
    priority: "High",
    category: "Bug",
    status: "Open",
    createdAt: "2023-10-27T13:45:00Z",
  },
  {
    id: "T-008",
    customerName: "Clint Barton",
    email: "hawkeye@farm.io",
    body: "I ordered 500 arrows but only received 499. This messes up my inventory count.",
    priority: "Low",
    category: "Billing",
    status: "Open",
    createdAt: "2023-10-27T14:00:00Z",
  },
  {
    id: "T-009",
    customerName: "T’Challa",
    email: "king@wakanda.gov",
    body: "We need an enterprise plan for the entire nation of Wakanda. Your current pricing page does not load for Vibranium IP addresses.",
    priority: "Medium",
    category: "Billing",
    status: "Open",
    createdAt: "2023-10-27T14:30:00Z",
  },
  {
    id: "T-010",
    customerName: "Scott Lang",
    email: "antman@quantumania.com",
    body: "The font size is too small when I shrink down. Can we get dynamic text scaling?",
    priority: "Medium",
    category: "Feature Request",
    status: "Open",
    createdAt: "2023-10-27T15:00:00Z",
  },
  {
    id: "T-011",
    customerName: "Stephen Strange",
    email: "doctor@sanctum.ny",
    body: "I am stuck in a time loop on the login page. I enter my password, it reloads, and asks for my password again.",
    priority: "High",
    category: "Bug",
    status: "Open",
    createdAt: "2023-10-27T15:30:00Z",
  },
  {
    id: "T-012",
    customerName: "Wade Wilson",
    email: "pool@dead.com",
    body: "WHY IS THERE NO CHIMICHANGA EMOJI SUPPORT??? 🌮 UNACCEPTABLE.",
    priority: "Low",
    category: "Feature Request",
    status: "Open",
    createdAt: "2023-10-27T16:00:00Z",
  },
  {
    id: "T-013",
    customerName: "Nick Fury",
    email: "director@shield.gov",
    body: "I need to know who accessed the dashboard last night. Send me the logs. Now.",
    priority: "High",
    category: "General",
    status: "Open",
    createdAt: "2023-10-27T16:30:00Z",
  },
  {
    id: "T-014",
    customerName: "Groot",
    email: "iam@groot.com",
    body: "I am Groot.",
    priority: "Low",
    category: "General",
    status: "Open",
    createdAt: "2023-10-27T17:00:00Z",
  },
  {
    id: "T-015",
    customerName: "Rocket",
    email: "trashpanda@galaxy.guardians",
    body: "Your API rate limits are trash. I’m going to hack your server if you don’t bump me to the Pro tier.",
    priority: "High",
    category: "Billing",
    status: "Open",
    createdAt: "2023-10-27T17:15:00Z",
  },
];
